// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANKAFYpUHeFqOuLg6eup1LRWlp-lfujzE',
    appId: '1:484383059885:web:0e2ea75b976fdf30207b24',
    messagingSenderId: '484383059885',
    projectId: 'career-growth-37c34',
    authDomain: 'career-growth-37c34.firebaseapp.com',
    storageBucket: 'career-growth-37c34.appspot.com',
    measurementId: 'G-GXZDZB4EPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0RXZpP9fXeJZd3mhYNkQBw9QQrGgPEh0',
    appId: '1:484383059885:android:fd84f3343f94fea0207b24',
    messagingSenderId: '484383059885',
    projectId: 'career-growth-37c34',
    storageBucket: 'career-growth-37c34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSkAnR53YO4PdteSxqnNLckgHxDodcgzI',
    appId: '1:484383059885:ios:1ffca1c979b92c2c207b24',
    messagingSenderId: '484383059885',
    projectId: 'career-growth-37c34',
    storageBucket: 'career-growth-37c34.appspot.com',
    iosBundleId: 'com.example.careerGrowth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSkAnR53YO4PdteSxqnNLckgHxDodcgzI',
    appId: '1:484383059885:ios:1ffca1c979b92c2c207b24',
    messagingSenderId: '484383059885',
    projectId: 'career-growth-37c34',
    storageBucket: 'career-growth-37c34.appspot.com',
    iosBundleId: 'com.example.careerGrowth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANKAFYpUHeFqOuLg6eup1LRWlp-lfujzE',
    appId: '1:484383059885:web:cb89ebaf2999b66f207b24',
    messagingSenderId: '484383059885',
    projectId: 'career-growth-37c34',
    authDomain: 'career-growth-37c34.firebaseapp.com',
    storageBucket: 'career-growth-37c34.appspot.com',
    measurementId: 'G-5B3HDHDPEW',
  );

}